// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wib.Api.Data;

#nullable disable

namespace Wib.Api.Migrations
{
    [DbContext(typeof(WibDbContext))]
    [Migration("20261001201934_AddStoreAndVouchers")]
    partial class AddStoreAndVouchers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wib.Api.Data.Entities.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CadenceDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("chores", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.ChoreCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CompletedByMemberId")
                        .HasColumnType("int");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("CompletedByMemberId");

                    b.ToTable("chore_completions", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.ChoreTag", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ChoreId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("chore_tags", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubjectId")
                        .IsUnique();

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.RewardItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("PointCost")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMemberId");

                    b.ToTable("reward_items", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnedByMemberId")
                        .HasColumnType("int");

                    b.Property<int>("PointCostSnapshot")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RewardItemId")
                        .HasColumnType("int");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OwnedByMemberId");

                    b.HasIndex("RewardItemId");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.ChoreCompletion", b =>
                {
                    b.HasOne("Wib.Api.Data.Entities.Chore", "Chore")
                        .WithMany("Completions")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wib.Api.Data.Entities.Member", "CompletedByMember")
                        .WithMany()
                        .HasForeignKey("CompletedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("CompletedByMember");
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.ChoreTag", b =>
                {
                    b.HasOne("Wib.Api.Data.Entities.Chore", "Chore")
                        .WithMany("ChoreTags")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wib.Api.Data.Entities.Tag", "Tag")
                        .WithMany("ChoreTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.RewardItem", b =>
                {
                    b.HasOne("Wib.Api.Data.Entities.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByMember");
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Voucher", b =>
                {
                    b.HasOne("Wib.Api.Data.Entities.Member", "OwnedByMember")
                        .WithMany("Vouchers")
                        .HasForeignKey("OwnedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wib.Api.Data.Entities.RewardItem", "RewardItem")
                        .WithMany()
                        .HasForeignKey("RewardItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnedByMember");

                    b.Navigation("RewardItem");
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Chore", b =>
                {
                    b.Navigation("ChoreTags");

                    b.Navigation("Completions");
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Member", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Wib.Api.Data.Entities.Tag", b =>
                {
                    b.Navigation("ChoreTags");
                });
#pragma warning restore 612, 618
        }
    }
}
